name: RSS Feed Notification Checker

on:
  schedule:
    - cron: "*/5 * * * *" # This will run the workflow every 1 minute
  workflow_dispatch: # This allows manual triggering of the workflow if needed

jobs:
  check_rss_feeds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9" # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run RSS Feed Checker Script
        run: python rss_monitor.py # Replace with the name of your Python script
